### ISSUE TITLE
avoid the 'sleep N' race conditions

### ISSUE THREAD

**Issue by praiskup** [sclorg/container-common-scripts#66]
E.g. #65, #62.  Basically, OpenShift isn't providing enough API for avoiding such hacks, but that should at least be discussed with openshift upstream so we know how to do proper scripting correctly.  Reading the openshift testing library (edit: i mean test-lib-openshift.sh), I more and more think that the library should be more than just testing library, but rather convenient library for daily work with openshift...

**Comment by pkubatrh** [comment]
>I more and more think that the library should be more than just testing library, but rather convenient library for daily work with openshift.

I agree, that would be really nice. I often find myself starting up the tests just so that I can get an instance for testing set up easier.

At least for #65 there should be a better solution via Openshift's api, but have to look into it more closer to make sure.
For #62 waiting for the pod running the registry might help a bit.

**Comment by pkubatrh** [comment]
Closed on accident, sorry for the noise.

**Comment by phracek** [comment]
The OpenShift 4 tests are solved by `oc` and `--json` output. The PRs mentioned in this issue are already closed.
We have also timeouts.
